# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dc791cced040d63ae6221f6b0fed4019d66d2182e46e88f4f951f220f130bab70e0ca251cb2ae6a90d98bfbbaa4b92b1a12b13580802f61f45a5f2ae95b205a3

test:
  secret_key_base: 3bc13e5d99b330474b150256a370585d0521be5c6f4d121af6eb08ddc94bb8edacc5b3ec01d10246cc21739ccc828217e9e2090f11359cd6c870ff84c269af5c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
